### ISSUE TITLE
There is no function to set merkle root for different epochs.

### ISSUE THREAD

**Issue by bibekblockchain** [Pastel-Software/Eth-Merkle-Distributor#1]
https://github.com/Pastel-Software/Eth-Merkle-Distributor/blob/b719ba510e68a3595bbfe9761134c5a7060f454a/contracts/ALMMerkleDistributor.sol#L7

**Comment by apurbapokharel** [comment]
the gist of new contract https://gist.github.com/apurbapokharel/3b51958567a0f49df5ed02aaf51a2e97
